### ISSUE TITLE
Can't run the example code

### ISSUE THREAD

**Issue by jaromiru** [microsoft/CyberBattleSim#17]
After installed, I ran the following:

```
$ python cyberbattle/agents/baseline/run.py --training_episode_count 1 --eval_episode_count 1 --iteration_count 10 --rewardplot_with 80  --chain_size=20 --ownership_goal 1.0
torch cuda available=False
###### DQL
Learning with: episode_count=1,iteration_count=10,ϵ=0.9,ϵ_min=0.1, ϵ_expdecay=5000,γ=0.015, lr=0.01, replaymemory=10000,
batch=512, target_update=10
  ## Episode: 1/1 'DQL' ϵ=0.9000, γ=0.015, lr=0.01, replaymemory=10000,
batch=512, target_update=10
Episode 1|Iteration 0|reward: ------|Elapsed Time: 0:00:00|                                                                                                                                                      |Traceback (most recent call last):
  File "cyberbattle/agents/baseline/run.py", line 77, in <module>
    dqn_learning_run = learner.epsilon_greedy_search(
  File "/home/jaromiru/Documents/wrk/rrl/CyberBattleSim/cyberbattle/agents/baseline/learner.py", line 257, in epsilon_greedy_search
    action_style, gym_action, action_metadata = learner.explore(wrapped_env)
  File "/home/jaromiru/Documents/wrk/rrl/CyberBattleSim/cyberbattle/agents/baseline/agent_dql.py", line 402, in explore
    gym_action = wrapped_env.env.sample_valid_action(kinds=[0, 1, 2])
  File "/home/jaromiru/Documents/wrk/rrl/CyberBattleSim/cyberbattle/_env/cyberbattle_env.py", line 938, in sample_valid_action
    action = self.sample_action_in_range(kinds)
  File "/home/jaromiru/Documents/wrk/rrl/CyberBattleSim/cyberbattle/_env/cyberbattle_env.py", line 884, in sample_action_in_range
    kind = np_random.choice(kinds)
AttributeError: 'NoneType' object has no attribute 'choice'
```

**Comment by jaromiru** [comment]
I wonder if there's a typo here (`self._np_random` instead of `self.np_random`):

https://github.com/microsoft/CyberBattleSim/blob/43a9108d83803ffbc3818b02fa13d9c613c79da8/cyberbattle/_env/discriminatedunion.py#L34

**Comment by blumu** [comment]
@jaromiru I remember hitting this bug when upgrading OpenAI gym. What version of the gym package to you have installed on your machine?

**Comment by jaromiru** [comment]
Hm, I checked and the error is present with gym `0.17.1`. I upgraded to `0.17.3` (as properly declared in the requirements.txt) and the error goes away.
